version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootSQL31415*
      MYSQL_DATABASE: ezpark_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - ezpark-network

  application:
    build: .
    ports:
      - "9192:9192"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ezpark_db
    networks:
      - ezpark-network

volumes:
  db_data:

networks:
  ezpark-network:
    driver: bridge